/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    /**
     *  Create a public method named getGreeting that returns a String "Hello World!".
     */

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }


}
